name: Publish

on:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - ".changeset/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Changeset versioning
        run: npx changeset version

      - name: Publish package to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push version updates
        run: |
          git add package.json package-lock.json
          git commit -m "Bump version to v$(node -p "require('./package.json').version")"
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
