name: Release & Publish

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'       # Make sure only TypeScript-related changes trigger the build
      - 'package.json'  # Trigger when package.json changes (e.g., version bump)

jobs:
  release:
    name: Version, Tag, Release, and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Run Changesets Versioning
        uses: changesets/action@v1
        with:
          version: npm run version-packages  # Bumps version based on changesets
          publish: npm run release  # Publishes package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token for tagging/releases
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # NPM Token for npm publishing
